version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cocktail_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: study
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
      LC_ALL: ko_KR.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: cocktail_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6.0
    container_name: cocktail_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cocktail_db
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  redis_data:
  mongo_data:
